POST http://localhost:3001/api/users/signup
Content-Type: application/json

{
    "name":"SteveJobs",
    "username":"stevejobs",
    "email":"steve.jobs@commercebear.com",
    "password":"steve123"
}