GET http://localhost:3001/api/users/5e33cef2f055d4650112b9b0
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNqb2JzIiwiaWQiOiI1ZTMzY2VmMmYwNTVkNDY1MDExMmI5YjAiLCJyb2xlIjoiVXNlciIsImlhdCI6MTU4MDQ1Mzc0OH0.lvynivLmSGnKM_JoUk1rWMbrUlg299m_watydHQ1Vxg

