//Admin Only
GET http://localhost:3001/api/users/admin
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJpbGxnYXRlcyIsImlkIjoiNWUzM2ViODA5YTc3Y2E4NTkxNjdkYmQ3Iiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNTgwNDYwOTg4LCJleHAiOjE1ODA0ODI1ODh9.eBdxTuRahZF-hgHJuoDXfuKBXibQFRCXWpXqUqVWvy0