GET http://localhost:3001/api/users/5e31946a8e8ad37a5f4eb389
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZTMxZTkyZmY1NGE1MGNkNTY4NmUwMzAiLCJ1c2VybmFtZSI6InNoZWhyeWFyIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNTgwMzI5MjgyfQ.hCyzgD90xbt5Ft35rzCfNdPccsoOYRIaml0LhsiKiVM