GET http://localhost:3001/api/subtasks/5e344197462e0aebf137476e
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJpbGxnYXRlcyIsImlkIjoiNWUzNDQwYjI5OGQyMjJlYWU3NDdmNDliIiwicm9sZSI6IlVzZXIiLCJpYXQiOjE1ODA0ODI3NTB9.BSbSyJdnIkdGtgsbEacaa0AS4BauW_Xu_1e6ufzB7RU
