PUT http://localhost:3001/api/subtasks/<id>
Content-Type: application/json
Authorization: Bearer 

{
    "title":"Sub-Gates Task -- 3--admin",
    "description":"Eat Breakfast at 8.45 am",
    "completed": true
}