PUT http://localhost:3001/api/subtasks/5e33bed591bc135033eb879f
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNqb2JzIiwiaWQiOiI1ZTMzYmI2NGE2MGY1NzRjNDFiNzJjZmEiLCJyb2xlIjoiVXNlciIsImlhdCI6MTU4MDQ0ODYxOX0.b_9SenjBtvqqSKDR_hNF51Yq185VB5OeL0_hRJl4bik


{
    "title":"Sub-Task -- 1",
    "description":"Eat Breakfast at 8.20 am",
    "completed": true,
    "todoId": "5e3005df9178646f7ee0a498"
}