DELETE http://localhost:3001/api/subtasks/5e344197462e0aebf137476e
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN3b3puaWFrIiwiaWQiOiI1ZTM0MmQ0MWQwNTE4NWQyM2E0YWM3NWYiLCJyb2xlIjoiVXNlciIsImlhdCI6MTU4MDQ3NzgwMH0.aELt0tfyRa8qzenEHAsvSDpRz6F0wzejrhbdeX-kH7M
