DELETE http://localhost:3001/api/subtasks/5e35503a4624291fd36b9180
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZXZlam9icyIsImlkIjoiNWUzNTc3Njk4OWQ3ZmY0YjY0MjFkYTA5Iiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNTgwNTYyMzAzfQ.ASrt5XIxT5HnRXrl2W90K8klUWrChZnKJKfVlfb0Ap8