POST http://localhost:3001/api/subtasks 
Content-Type: application/json

{
    "title":"Sub-Task -- 2",
    "description":"Pick up eggs on the drive back",
    "completed": false,
    "todoId": "5e3040db5fbf0da2b390ecc9",
    "userId": "5e3040c35fbf0da2b390ecc8"
}