PUT http://localhost:3001/api/subtasks/5e2ffdd56b5eb6666f38d7e2
Content-Type: application/json

{
    "title":"Sub-Task -- 1",
    "description":"Eat Breakfast at 8.20 am",
    "completed": false,
    "todoId": "5e3005df9178646f7ee0a498",
    "userId": "5e300251b6b22b6bde1a00a0"
}