POST http://localhost:3001/api/todos
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJpbGxnYXRlcyIsImlkIjoiNWUzNTQ3NjRhMzVmZTAxNjhmYzUyMDEwIiwicm9sZSI6IlVzZXIiLCJpYXQiOjE1ODA1NTAwMDV9.qf9pQ1O994aQQ9SEun90lZngYjukUglQL87h_-rEX9M


{  
    "title":"Bill Gates first task",
    "description":"Do snow removal",
    "completed": false
}
