POST http://localhost:3001/api/todos
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0ZXZlam9icyIsImlkIjoiNWUzNTk5MTNkM2ZlM2I1ODQyMjgxZjEyIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNTgwNTcwOTA2fQ.0jOEJ2ELz2D8CpgXGbzrOylCY4VPiOdlBTf0dz_cKLE

{  
    "title":"Steve's Admin Status first task",
    "description":"Do snow removal",
    "completed": false
}
