//View todos by Id
GET http://localhost:3001/api/todos/5e3440d098d222eae747f49c
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJpbGxnYXRlcyIsImlkIjoiNWUzNDQwYjI5OGQyMjJlYWU3NDdmNDliIiwicm9sZSI6IlVzZXIiLCJpYXQiOjE1ODA0ODI3NTB9.BSbSyJdnIkdGtgsbEacaa0AS4BauW_Xu_1e6ufzB7RU
