PUT http://localhost:3001/api/todos/<id>
Content-Type: application/json
Authorization: Bearer 

{
    "title":"Change Sam's first task ",
    "description":"Testing admin privileges",
    "completed": false
}