PUT http://localhost:3001/api/todos/5e338e706b9a98134ede42f8/completed
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNqb2JzIiwiaWQiOiI1ZTMzOGEyYjg4YTcyZjBlNmFjMTcwYjIiLCJyb2xlIjoiVXNlciIsInRvZG9BdXRoIjoiNWUzMzhhMmI4OGE3MmYwZTZhYzE3MGIyIiwiaWF0IjoxNTgwNDM3OTU2fQ.Q5yCOIrIge_RGGyFhHcPtTN6zY6CDuO-rQdq1Ab-lZU

{
    "completed": false
}