POST http://localhost:3001/api/todos 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNoZWhyeWFyQmFqd2EiLCJpZCI6IjVlMzBhMjc1NDRhOGUxNDFiMWNjZmEzZSIsImlhdCI6MTU4MDI5OTUwOH0.1TYyH7q5tIzxJyfttFx2B0sbOnaK6uwiJbwlNdNkwxk

{
    "title":"Task -- 5",
    "description":"Pick Jacob from Work",
    "completed": false,
    "userId": "5e30a27544a8e141b1ccfa3e"
}