//Admin Only - View all Todos
GET http://localhost:3001/api/todos/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZTMyMzQ5NTM5Y2M4MTAyMTk4YjIzZjgiLCJ1c2VybmFtZSI6InNqdW9icyIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNTgwMzU2MjM4fQ.Bu02TJ5XqY86c5sBliVYULgDJe-YDz82kw3ZtsMLOxY