PUT http://localhost:3001/api/todos/5e2fe8a54d7cd443c1199339
Content-Type: application/json

{
    "title":"First important task",
    "description":"Wake up early",
    "completed": false,
    "userId": "5e2fe5be9225dc3dabccd33a"
}